# Generated by Django 4.2.2 on 2023-06-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverify',
            options={'verbose_name': '이메일 인증번호', 'verbose_name_plural': '이메일 인증번호'},
        ),
        migrations.RenameField(
            model_name='emailverify',
            old_name='phone_number',
            new_name='email',
        ),
    ]
