# Generated by Django 4.2.2 on 2023-06-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_emailverify_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_secret',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='비밀번호 찾기(인증번호)'),
        ),
    ]
