# Generated by Django 4.2.2 on 2023-06-16 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '기초 기획안 작성',
                'verbose_name_plural': '기초 기획안 작성',
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '최종컨펌',
                'verbose_name_plural': '최종컨펌',
            },
        ),
        migrations.CreateModel(
            name='Filming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '촬영(계획/진행)',
                'verbose_name_plural': '촬영(계획/진행)',
            },
        ),
        migrations.CreateModel(
            name='PostWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '후반 작업',
                'verbose_name_plural': '후반 작업',
            },
        ),
        migrations.CreateModel(
            name='Storyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '스토리보드 작성',
                'verbose_name_plural': '스토리보드 작성',
            },
        ),
        migrations.CreateModel(
            name='VideoDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '영상 납품',
                'verbose_name_plural': '영상 납품',
            },
        ),
        migrations.CreateModel(
            name='VideoEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '비디오 편집',
                'verbose_name_plural': '비디오 편집',
            },
        ),
        migrations.CreateModel(
            name='VideoPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='시작 날짜')),
                ('end_date', models.DateTimeField(verbose_name='끝나는 날짜')),
            ],
            options={
                'verbose_name': '비디오 시사',
                'verbose_name_plural': '비디오 시사',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='프로젝트 이름')),
                ('unique_number', models.CharField(max_length=100, unique=True, verbose_name='프로젝트ID')),
                ('manager', models.CharField(max_length=50, verbose_name='담당자')),
                ('consumer', models.CharField(max_length=50, verbose_name='고객사')),
                ('description', models.TextField(blank=True, verbose_name='프로젝트 설명')),
                ('basic_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.basicplan', verbose_name='기초 기획안 작성')),
                ('confirmation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.confirmation', verbose_name='최종컨펌')),
                ('filming', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.filming', verbose_name='촬영')),
                ('post_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.postwork', verbose_name='후반 작업')),
                ('story_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.storyboard', verbose_name='스토리보드 작성')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
                ('video_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.videodelivery', verbose_name='영상 납품')),
                ('video_edit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.videoedit', verbose_name='비디오 편집')),
                ('video_preview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.videopreview', verbose_name='비디오 시사')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(default='normal', max_length=10, verbose_name='권한')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project', verbose_name='프로젝트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(upload_to='project_file', verbose_name='프로젝트 파일')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='프로젝트')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
