# Generated by Django 4.2.2 on 2023-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unique_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='프로젝트ID'),
        ),
    ]
