# Generated by Django 4.2.2 on 2023-06-19 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_unique_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '1.프로젝트', 'verbose_name_plural': '1.프로젝트'},
        ),
    ]
