# Generated by Django 4.2.2 on 2023-06-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='unique_number',
        ),
        migrations.CreateModel(
            name='ProjectInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='projects.project', verbose_name='프로젝트')),
                ('users', models.ManyToManyField(blank=True, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='초대 된 사용자')),
            ],
            options={
                'verbose_name': '프로젝트 초대',
                'verbose_name_plural': '프로젝트 초대',
            },
        ),
    ]
