# Generated by Django 4.2.2 on 2023-06-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_unique_number_projectinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvite',
            name='users',
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='초대된 이메일'),
        ),
    ]
