# Generated by Django 4.2.2 on 2023-06-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_projectinvite_users_projectinvite_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="rating",
            field=models.CharField(
                choices=[("manager", "준관리자"), ("normal", "일반회원")],
                default="normal",
                max_length=10,
                verbose_name="권한",
            ),
        ),
    ]
