# Generated by Django 4.2.2 on 2023-06-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0004_remove_feedback_project"),
        ("projects", "0006_alter_members_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="feedback",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="feedbacks.feedback",
                verbose_name="피드백",
            ),
        ),
    ]
