# Generated by Django 4.2.2 on 2023-06-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_project_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="color",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="색상"
            ),
        ),
    ]
