# Generated by Django 4.2.2 on 2023-06-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_project_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="basic_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.basicplan",
                verbose_name="기초 기획안 작성",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="confirmation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.confirmation",
                verbose_name="최종컨펌",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="filming",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.filming",
                verbose_name="촬영",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="post_work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.postwork",
                verbose_name="후반 작업",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="story_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.storyboard",
                verbose_name="스토리보드 작성",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.videodelivery",
                verbose_name="영상 납품",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_edit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.videoedit",
                verbose_name="비디오 편집",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_preview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.videopreview",
                verbose_name="비디오 시사",
            ),
        ),
    ]
