# Percy visual regression testing configuration
version: 2

# Snapshot configuration
snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet  
    - 1280  # Desktop
    - 1920  # Large Desktop
  
  min-height: 1024
  
  # Percy-specific options
  percy-css: |
    /* Hide dynamic elements that cause visual flakes */
    [data-testid="loading-spinner"],
    [data-testid="timestamp"],
    [data-testid="real-time-counter"],
    .animate-pulse,
    .animate-spin {
      display: none !important;
    }
    
    /* Stabilize animations */
    *,
    *::before,
    *::after {
      animation-duration: 0s !important;
      animation-delay: 0s !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
    
    /* Hide scrollbars for consistent snapshots */
    ::-webkit-scrollbar {
      display: none;
    }
    
    /* Ensure consistent font rendering */
    body {
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
    }

# Discovery configuration  
discovery:
  allowed-hostnames:
    - localhost
    - 127.0.0.1
  
  network-idle-timeout: 750
  
  disable-cache: true
  
# Agent configuration
agent:
  asset-discovery:
    allowed-hostnames:
      - localhost
      - 127.0.0.1
      - fonts.googleapis.com
      - fonts.gstatic.com
  
  # Client/Server communication timeout
  client-timeout: 600000
  
  # Environment-specific settings
  env:
    CI:
      # CI-specific Percy settings
      parallel-nonce: ${PERCY_PARALLEL_NONCE}
      parallel-total: ${PERCY_PARALLEL_TOTAL}
    
# Static asset serving
static-snapshots: false

# Debugging
debug: false

# Defer uploads in development
defer-uploads: false