# Railway Nixpacks 설정 - 강제로 Node.js 프로젝트로 인식
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.build]
dependsOn = ["setup"]
cmds = [
  "cd vridge-web && pnpm install --frozen-lockfile",
  "cd vridge-web && pnpm run build"
]

[phases.start]
cmd = "cd vridge-web && pnpm run start"

[variables]
NODE_ENV = "production"
PORT = "3000"