# Railway Django Backend Configuration

[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate --noinput && daphne -b 0.0.0.0 -p $PORT config.asgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
DJANGO_SETTINGS_MODULE = "config.settings"
DEBUG = "False"
ALLOWED_HOSTS = "*.railway.app,*.up.railway.app,localhost,127.0.0.1"
CORS_ALLOWED_ORIGINS = "https://vridge-web.vercel.app,https://videoplanet.vercel.app"