# Generated by Django 4.2.2 on 2023-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackcomment',
            name='section',
            field=models.CharField(max_length=50, null=True, verbose_name='구간'),
        ),
        migrations.AddField(
            model_name='feedbackcomment',
            name='security',
            field=models.BooleanField(default=False, verbose_name='익명'),
        ),
        migrations.AddField(
            model_name='feedbackcomment',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='feedbackcomment',
            name='text',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
    ]
