# Generated by Django 4.2.2 on 2023-06-26 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_members_rating"),
        ("feedbacks", "0002_feedbackcomment_section_feedbackcomment_security_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="projects.project",
                verbose_name="프로젝트",
            ),
        ),
    ]
