# Generated by Django 4.2.2 on 2023-06-26 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0003_alter_feedback_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="project",
        ),
    ]
