# Generated by Django 4.2.2 on 2023-06-27 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("feedbacks", "0004_remove_feedback_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackcomment",
            options={
                "ordering": ("-created",),
                "verbose_name": "피드백 등록",
                "verbose_name_plural": "피드백 등록",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackmessage",
            options={"verbose_name": "피드백 대화방", "verbose_name_plural": "피드백 대화방"},
        ),
    ]
